# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banks.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61nks.proto\x12\x04\x62\x61nk\"L\n\x12TransactionRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"6\n\x13TransactionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\x32J\n\x04\x42\x61nk\x12\x42\n\x0bMsgDelivery\x12\x18.bank.TransactionRequest\x1a\x19.bank.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=21
  _globals['_TRANSACTIONREQUEST']._serialized_end=97
  _globals['_TRANSACTIONRESPONSE']._serialized_start=99
  _globals['_TRANSACTIONRESPONSE']._serialized_end=153
  _globals['_BANK']._serialized_start=155
  _globals['_BANK']._serialized_end=229
# @@protoc_insertion_point(module_scope)
